apiVersion: apps/v1
kind: Deployment
metadata: 
  name: React-app
spec:
  replicas: 1
  selector:
    matchlabels:
      app: React-app
template:
  metadata:
    labels:
      app: React-app
  spec:
    containers:
    - name: React-app-c1
      image: Jithesh0017/react-app
      ports:
      - containerPort: 80
