name: app
on: workflow_dispatch
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: build docker image
        run: docker build -t ${{ vars.DH_USERNAME }}/react-app .
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: docker push image
        run: docker push ${{ vars.DH_USERNAME }}/react-app
  deploy:
    runs-on: self-hosted
    needs: app
    steps:
      - name: docker pull
        run: sudo docker pull ${{ vars.DH_USERNAME }}/react-app
      - name: docker container
        run: sudo docker container run -dt --name loll -p 8112:80 ${{ vars.DH_USERNAME }}/react-app
      - name: container list
        run: sudo docker container ls
