name: edify-docker
on: workflow_dispatch
jobs:
  edify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker build
        run: docker build -t ${{ vars.DC_USERNAME }}/edify-app:latest .
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DC_USERNAME }}
          password: ${{ secrets.DC_PASSWORD }}
      - name: docker push
        run: docker push ${{ vars.DC_USERNAME }}/edify-app:latest
  deploy:
    needs: edify
    runs-on: self-hosted
    steps:
      - name: docker pull image
        run: docker pull ${{ vars.DC_USERNAME }}/edify-app:latest
      - name: docker container pull
        run: docker container run -dt --name edify -p 80:80 ${{ vars.DC_USERNAME }}/edify-app:latest
      - name: list container
        run: docker container ls
        
