name: app
on: workflow_dispatch
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: setup nodejs
        uses: actions/setup-node@3.9.1
        with:
          node-version: 20
      - name: remove nginx
        run: sudo rm -rf /usr/share/nginx/html/*
      - name: git clone react-app
        run: sudo git clone https://github.com/Jithesh0017/react-app.git /usr/share/nginx/html
      - name: docker build
        run: docker build -t ${{ vars.DH_USERNAME }}/react-app:latest .
      - name: docker push 
        run: docker push ${{ vars.DH_USERNAME }}/react-app:latest
  deploy:
    needs: app
    runs-on: deploy
    steps:
      - name: docker pull
        run: sudo docker pull ${{ vars.DH_USERNAME }}/react-app:latest
      - name: docker container
        run: sudo docker container run -dt --name karma -p 8094:80 ${{ vars.DH_USERNAME }}/react-app:latest
      - name: container list
        run: sudo docker container ls
